/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HuertoSerenoRouteImport } from './routes/huerto-sereno'
import { Route as CosmosBiodinamicoRouteImport } from './routes/cosmos-biodinamico'
import { Route as IndexRouteImport } from './routes/index'

const HuertoSerenoRoute = HuertoSerenoRouteImport.update({
  id: '/huerto-sereno',
  path: '/huerto-sereno',
  getParentRoute: () => rootRouteImport,
} as any)
const CosmosBiodinamicoRoute = CosmosBiodinamicoRouteImport.update({
  id: '/cosmos-biodinamico',
  path: '/cosmos-biodinamico',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cosmos-biodinamico': typeof CosmosBiodinamicoRoute
  '/huerto-sereno': typeof HuertoSerenoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cosmos-biodinamico': typeof CosmosBiodinamicoRoute
  '/huerto-sereno': typeof HuertoSerenoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cosmos-biodinamico': typeof CosmosBiodinamicoRoute
  '/huerto-sereno': typeof HuertoSerenoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cosmos-biodinamico' | '/huerto-sereno'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cosmos-biodinamico' | '/huerto-sereno'
  id: '__root__' | '/' | '/cosmos-biodinamico' | '/huerto-sereno'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CosmosBiodinamicoRoute: typeof CosmosBiodinamicoRoute
  HuertoSerenoRoute: typeof HuertoSerenoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/huerto-sereno': {
      id: '/huerto-sereno'
      path: '/huerto-sereno'
      fullPath: '/huerto-sereno'
      preLoaderRoute: typeof HuertoSerenoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cosmos-biodinamico': {
      id: '/cosmos-biodinamico'
      path: '/cosmos-biodinamico'
      fullPath: '/cosmos-biodinamico'
      preLoaderRoute: typeof CosmosBiodinamicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CosmosBiodinamicoRoute: CosmosBiodinamicoRoute,
  HuertoSerenoRoute: HuertoSerenoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
